SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Altering [dbo].[Space]'
GO
ALTER TABLE [dbo].[Space] ADD
[UrlSlug] [nvarchar] (256) NULL
GO

